<?php

class Member
{
    //Fields for Personal Information
    private $_fname;
    private $_lname;
    private $_age;
    private $_gender;
    private $_phone;
    private $_email;
    private $_state;
    private $_seekingGender;
    private $_bio;

    public function __construct()
    {
        $this->_fname = "";
        $this->_lname = "";
        $this->_age = -1;
        $this->_gender = "";
        $this->_state = "";

        $this->_bio = "";
        $this->_seekingGender = "";

        $this->_phone = "";
        $this->_email = "";
    }

    // Autogenerated getters and setters using default constructor types

    /**
     * @return string
     */
    public function getFname(): string
    {
        return $this->_fname;
    }

    /**
     * @param string $_fname
     */
    public function setFname(string $_fname): void
    {
        $this->_fname = $_fname;
    }

    /**
     * @return string
     */
    public function getLname(): string
    {
        return $this->_lname;
    }

    /**
     * @param string $_lname
     */
    public function setLname(string $_lname): void
    {
        $this->_lname = $_lname;
    }

    /**
     * @return int
     */
    public function getAge(): int
    {
        return $this->_age;
    }

    /**
     * @param int $_age
     */
    public function setAge(int $_age): void
    {
        $this->_age = $_age;
    }

    /**
     * @return string
     */
    public function getGender(): string
    {
        return $this->_gender;
    }

    /**
     * @param string $_gender
     */
    public function setGender(string $_gender): void
    {
        $this->_gender = $_gender;
    }

    /**
     * @return string
     */
    public function getState(): string
    {
        return $this->_state;
    }

    /**
     * @param string $_state
     */
    public function setState(string $_state): void
    {
        $this->_state = $_state;
    }

    /**
     * @return string
     */
    public function getBio(): string
    {
        return $this->_bio;
    }

    /**
     * @param string $_bio
     */
    public function setBio(string $_bio): void
    {
        $this->_bio = $_bio;
    }

    /**
     * @return string
     */
    public function getSeekingGender(): string
    {
        return $this->_seekingGender;
    }

    /**
     * @param string $_seekingGender
     */
    public function setSeekingGender(string $_seekingGender): void
    {
        $this->_seekingGender = $_seekingGender;
    }

    /**
     * @return string
     */
    public function getPhone(): string
    {
        return $this->_phone;
    }

    /**
     * @param string $_phone
     */
    public function setPhone(string $_phone): void
    {
        $this->_phone = $_phone;
    }

    /**
     * @return string
     */
    public function getEmail(): string
    {
        return $this->_email;
    }

    /**
     * @param string $_email
     */
    public function setEmail(string $_email): void
    {
        $this->_email = $_email;
    }




}