<?php

class Profile
{
    //Fields for Personal Information
    private $name;
    private $age;
    private $gender;
    private $state;

    //Fields for Dating Matchmaking
    private $bio;
    private $seekingGender;
    private $outdoorInterests;
    private $indoorInterests;

    //Fields for Contact Information
    private $phone;
    private $email;


    public function __construct()
    {
        $this->name = "";
        $this->age = -1;
        $this->gender = "";
        $this->state = "";

        $this->bio = "";
        $this->seekingGender = "";
        $this->outdoorInterests = array();
        $this->indoorInterests = array();

        $this->phone = "";
        $this->email = "";
    }

    // Autogenerated getters and setters using default constructor types

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return int
     */
    public function getAge(): int
    {
        return $this->age;
    }

    /**
     * @param int $age
     */
    public function setAge(int $age): void
    {
        $this->age = $age;
    }

    /**
     * @return string
     */
    public function getGender(): string
    {
        return $this->gender;
    }

    /**
     * @param string $gender
     */
    public function setGender(string $gender): void
    {
        $this->gender = $gender;
    }

    /**
     * @return string
     */
    public function getState(): string
    {
        return $this->state;
    }

    /**
     * @param string $state
     */
    public function setState(string $state): void
    {
        $this->state = $state;
    }

    /**
     * @return string
     */
    public function getBio(): string
    {
        return $this->bio;
    }

    /**
     * @param string $bio
     */
    public function setBio(string $bio): void
    {
        $this->bio = $bio;
    }

    /**
     * @return string
     */
    public function getSeekingGender(): string
    {
        return $this->seekingGender;
    }

    /**
     * @param string $seekingGender
     */
    public function setSeekingGender(string $seekingGender): void
    {
        $this->seekingGender = $seekingGender;
    }

    /**
     * @return array
     */
    public function getOutdoorInterests(): array
    {
        return $this->outdoorInterests;
    }

    /**
     * @param array $outdoorInterests
     */
    public function setOutdoorInterests(array $outdoorInterests): void
    {
        $this->outdoorInterests = $outdoorInterests;
    }

    /**
     * @return array
     */
    public function getIndoorInterests(): array
    {
        return $this->indoorInterests;
    }

    /**
     * @param array $indoorInterests
     */
    public function setIndoorInterests(array $indoorInterests): void
    {
        $this->indoorInterests = $indoorInterests;
    }

    /**
     * @return string
     */
    public function getPhone(): string
    {
        return $this->phone;
    }

    /**
     * @param string $phone
     */
    public function setPhone(string $phone): void
    {
        $this->phone = $phone;
    }

    /**
     * @return string
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }




}